<div class="actions actions-get-token">
    <button class="actions-get-token" type="button" id="<?= /** @noEscape */ $block->getHtmlId() ?>">
        <span><?= /** @noEscape */ $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<script type="text/x-magento-init">
    {
        "#mpinstagramfeed_general_token": {
            "tribugs/auth": {
                "ajaxUrl": "<?= /** @noEscape */ $block->getButtonUrl() ?>"
            }
        }
    }
</script>
