<?php

/** @var Tribugs\InstagramFeed\Block\Widget $block */
if ($block->isEnable()):
    $widgetId = uniqid('-', false);
    $options = $block->getAllOptions();
    $total = $options['total_number'];
    $calcWidth = $block->calcWidth();
    $width = $block->getNumberRow($options['layout']) ? $calcWidth . '%' : $calcWidth . 'px';
    $sizeIcon = ($calcWidth < 10) ? '10px' : '14px';
    ?>
    <div class="mpinstagramfeed-container">
        <div class="mpinstagramfeed-header">
            <h3><?= /** @noEscape */ __($block->getData('title')) ?></h3>
            <div><?= /** @noEscape */ __($block->getData('description')) ?></div>
        </div>
        <div id="mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId ?>" class="row shuffle"></div>
    </div>
    <style type="text/css">
        #mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId?> .mpinstagramfeed-photo {
            width: calc(<?= /** @noEscape */ $width ?> - 4px);
        }
        #mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId?> .mpinstagramfeed-video {
            width: calc(<?= /** @noEscape */ $width ?> - 4px);
        }
        .mpinstagramfeed-container .mpinstagramfeed-photo .mpinstagramfeed-post-caption {
            font-size: <?= /** @noEscape */ $sizeIcon ?>;
        }
        .mpinstagramfeed-container .mpinstagramfeed-video .mpinstagramfeed-post-caption {
            font-size: <?= /** @noEscape */ $sizeIcon ?>;
        }
        @media (max-width: 767px) {
            .mpinstagramfeed-container #mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId ?> .mpinstagramfeed-photo {
                width: 100%;
            }
            .mpinstagramfeed-container #mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId ?> .mpinstagramfeed-photo.shuffle-item {
                width: auto;
            }
            .mpinstagramfeed-container #mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId ?> .mpinstagramfeed-video {
                width: 100%;
            }
            .mpinstagramfeed-container #mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId ?> .mpinstagramfeed-video.shuffle-item {
                width: auto;
            }
        }
        @media (min-width: 767px) and (max-width: 1024px) {
            .mpinstagramfeed-container #mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId ?> .mpinstagramfeed-photo {
                width: 30%;
            }
            .mpinstagramfeed-container #mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId ?> .mpinstagramfeed-photo.shuffle-item {
                width: auto;
            }
            .mpinstagramfeed-container #mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId ?> .mpinstagramfeed-video {
                width: 30%;
            }
            .mpinstagramfeed-container #mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId ?> .mpinstagramfeed-video.shuffle-item {
                width: auto;
            }
        }
    </style>
    <script type="text/x-magento-init">
    {
        "#mpinstagramfeed-photos-<?= /** @noEscape */ $widgetId ?>": {
            "tribugs/instagram": {
                "id": "<?= /** @noEscape */ $widgetId ?>",
                "token": "<?= /** @noEscape */ $block->getAccessToken() ?>",
                "count": "<?= /** @noEscape */ $total ?>",
                "layout": "<?= /** @noEscape */ $options['layout'] ?>",
                "show_caption": "<?= /** @noEscape */ $options['show_caption'] ?>",
                "show_popup": "<?= /** @noEscape */ $options['show_popup'] ?>"
            }
        }
    }
    </script>
<?php endif; ?>
